# Generated by Django 4.2.4 on 2024-07-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiflutter', '0003_task_comments_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
