# Generated by Django 4.2.4 on 2024-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiflutter', '0006_remove_task_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
