# Generated by Django 4.2.4 on 2024-08-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiflutter', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
