# Generated by Django 4.2.4 on 2024-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiflutter', '0012_remove_task_image_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
